### ISSUE TITLE
Does Chroma shader variant scale also LUMA?

### ISSUE THREAD

**Issue by CrHasher** [Artoriuz/ArtCNN#10]
Does one have to use both non chroma and chroma variants to scale both luma and chroma aka:

```
glsl-shader="~~/shaders/ArtCNN_C4F16.glsl"
glsl-shader="~~/shaders/ArtCNN_C4F16_Chroma.glsl"
```

or does the Chroma version scale both LUMA and CHROMA?

**Comment by Artoriuz** [comment]
Use the YCbCr variants if you want to scale both luma and chroma, just remember to set `cscale=bilinear`.
