### ISSUE TITLE
Optimization for live action content?

### ISSUE THREAD

**Issue by crazysword1** [Artoriuz/ArtCNN#11]
With the exception of the DIV2K variant, all the other shaders were trained on the Manga109 dataset.

Would it be possible for you to also have the DIV2K variant for ArtCNN_C4F8? (Laptop not powerful enough to run C4F16).

.Alternatively, if most of the media I consume is live action, would you recommend that I use ravu-zoom-ar-r3 or FSRCNNX instead of ArtCNN?

Thank you

**Comment by Artoriuz** [comment]
I'd be more inclined to just remove the DIV2K variant and all the C4F8 variants to be honest. There's too much bloat currently.

About ravu-zoom-ar-r3 vs FSRCNNX, I personally prefer ravu. For live-action I don't think this choice matters that much, either is fine.
