### ISSUE TITLE
How to use as fractional scaler?

### ISSUE THREAD

**Issue by AlifianK** [Artoriuz/ArtCNN#12]
The README says it can be used as a fractional upscaler, I tried 720p source on a 1366x768 screen and it doesn't work, how should I do that? I'm sorry if this is an obvious question.

**Comment by Artoriuz** [comment]
In your case the scaling factor is too small for it to trigger. You can edit the WHEN condition within the shader if you want to though.

**Comment by AlifianK** [comment]
I see, thanks.
