### ISSUE TITLE
Request: C4F8 Chroma variant

### ISSUE THREAD

**Issue by Dkfc123** [Artoriuz/ArtCNN#13]
Would you consider making one?

**Comment by Artoriuz** [comment]
The chroma variant needs to output 2 distinct channels, and C4F8 is simply not good enough to do this without blocking/aliasing. I'd rather work on making C4F16 faster than waste time on a model that's intrinsically too small for the task.

**Comment by Dkfc123** [comment]
That would work too, C4F16 Chroma on a native res 1080 24p video gets me into the low 50s (My display is 60hz) 

btw thanks for all of the effort you put into your shaders !!
