### ISSUE TITLE
`//!COMPONENTS 4` pragma is missing in shaders

### ISSUE THREAD

**Issue by bjin** [Artoriuz/ArtCNN#2]
Without this pragma, last component (`.w`) in the output texture might be truncated

**Comment by Artoriuz** [comment]
Done, thanks =)

**Comment by kasper93** [comment]
Some of the variants are still missing it

**Comment by Artoriuz** [comment]
I fucked up at some point when I started retraining and renaming them yesterday (I think). Gonna fix it again soon, thanks.
