### ISSUE TITLE
_DS_CMP shaders aren't working?

### ISSUE THREAD

**Issue by Trinity3e** [Artoriuz/ArtCNN#21]
Here's what mpv says:

> [vo/gpu-next/libplacebo] shader compile log (status=0): 0:67(12): warning: extension `GL_EXT_shader_explicit_arithmetic_types_float16' unsupported in compute shader
> [vo/gpu-next/libplacebo] 0:67(1): error: #extension directive is not allowed in the middle of a shader

Thanks in advance

**Comment by Artoriuz** [comment]
All three of them compile just fine here, maybe this is unsupported by your driver/GPU?

**Comment by Jules-A** [comment]
I haven't checked the logs yet but the CMP versions were still failing for me under DX11.

**Comment by Trinity3e** [comment]
The normal _CMP ones work fine, I will try again and play around with some configs.

LE: Huh, found the reason, it needs gpu-api=vulkan. It's very weird. Probably a bug turned feature somewhere which allows plain _CMP to work without vulkan but not _CMP_DS. I guess i'll close this but please mention this in the readme. I am on amdgpu.

**Comment by Artoriuz** [comment]
The shader gen code is the same so they should have the same issues... I'm currently generating the compute shaders again with Kasper's new changes so feel free to give it another go soon.

**Comment by Jules-A** [comment]
> The shader gen code is the same so they should have the same issues... I'm currently generating the compute shaders again with Kasper's new changes so feel free to give it another go soon.

Compiles under DX11 now and speed is about the same as gather for C4F32 under DX11, under Vulkan it's slightly slower than previous version though.

EDIT: I checked why it failed on previous version in log: 
```
[  16.309][e][vo/gpu-next/libplacebo] D3DCompile failed: Unspecified error (E_FAIL, 0x80004005)
[  16.309][e][vo/gpu-next/libplacebo] error X4586: The total amount of group shared memory (41472 bytes) exceeds the cs_5_0 limit of 32768 bytes
```

Not the same error as OP.
