### ISSUE TITLE
lighter chroma upscale

### ISSUE THREAD

**Issue by ofirielon** [Artoriuz/ArtCNN#26]
why isnt there a lighter chroma upscale than f32? what happened to 16?

**Comment by Artoriuz** [comment]
The chroma model needs to generate 2 channels simultaneously and it just didn't work as well as I wanted it to with only 16 filters per layer. It also doesn't get along nicely with luma doublers which makes its use-case very narrow (native res video).

The rationale is just that if you're interested in using a CNN to restore chroma on native res content, then you probably have compute power to spare and can run C4F32.
