### ISSUE TITLE
Hope to add a non-super-resolution version, similar to Anime4K_Restore.

### ISSUE THREAD

**Issue by AcerolaShinobu** [Artoriuz/ArtCNN#27]
Whether it’s super-resolution after frame interpolation or frame interpolation after super-resolution, the performance requirements are too high. I hope to use ArtCNN_Restore before frame interpolation and then apply other upscaling methods after frame Interpolation, with minimal impact on performance.

**Comment by Artoriuz** [comment]
A 1x image restoration model isn't on my radar right now. That's technically trivial to do from an architectural and training perspective, but you have to be very careful when choosing the degradation model.

If you make the model too strong it'll denoise too much and get rid of fine-detail, but if you make it too weak you probably won't even notice the difference (specially if you plan on scaling the image with something else afterwards).
