### ISSUE TITLE
Does it only work for Anime?

### ISSUE THREAD

**Issue by laichiaheng** [Artoriuz/ArtCNN#29]
I'm looking for a good upscaler for general contents, but most of them are based on Anime.

**Comment by Trinity3e** [comment]
I wanted to ask basically the same thing a week ago here, thank you for breaking the ice by the way!
i use ArtCNN a lot now, and for mostly real/general content as well (it works ok, especially cmp which are more efficient that fsrcnnx/ravu) and i was thinking about whether simply including some real images in the training set next to the anime ones (do only the chroma shaders have DIV2K? @Artoriuz ) would make this an even more universal shader while still keeping importance on the art sources it was made for.

**Comment by Artoriuz** [comment]
I thought about releasing a DIV2K variant again, but the TLDR after various experiments is that it doesn't really matter that much.

I'll leave this here if you really feel inclined, just don't expect it to look radically different.
[ArtCNN_C4F16_DIV2K_CMP.txt](https://github.com/user-attachments/files/16826042/ArtCNN_C4F16_DIV2K_CMP.txt)

**Comment by Trinity3e** [comment]
Had a look at it and have to say it certainly seems more natural, thank you.
If you don't mind and only if, as long as it's easy enough, can you have the rest of the CMP ones done?
