### ISSUE TITLE
Blue/black screen using ARTcnn

### ISSUE THREAD

**Issue by waffle2022** [Artoriuz/ArtCNN#30]
Hi, I wasn't able to use ARTcnn, I would be glad if you guys checked my mpv config, maybe it has something to do with vulkan or with default upscalers? The shaders are seen running with the shaders info though

fullscreen
stop-screensaver
profile=gpu-hq
gpu-api=vulkan
spirv-compiler=shaderc
--fbo-format=rgba16f
lanczos with linear-downscaling=no

deband=yes
deband-iterations=6
deband-threshold=64
deband-grain=0

interpolation=yes
tscale=box
tscale-window=sphinx
tscale-radius=1.0
tscale-clamp=0.0

scale-antiring=0.7
dscale-antiring=0.7
cscale-antiring=0.7

blend-subtitles=yes

target-prim=auto
target-trc=auto

sub-font="ITCFranklinGothic LT MedCn"
sub-font-size=42
sub-border-size=2.75
sub-border-color="#C8111111"
sub-shadow-offset=1
sub-shadow-color="#3C101010"
sub-color="#E6FFFFFF"

sub-gray

audio-channels=auto

screenshot-format=png
screenshot-directory=C:\Users\edoar\OneDrive\Immagini

[4:2:0]
profile-cond=((p["video-params/pixelformat"] == "yuv420p10" or p["video-params/pixelformat"] == "yuv420p"))

cscale=ewa_lanczossoft

[720p-1080p]
profile-cond=height >= 720 and height < 1080
glsl-shader="~~/shaders/ArtCNN_C4F16.glsl"

[480p-720p]
profile-cond=height >= 640 and height < 480
glsl-shader="~~/shaders/nnedi3-nns128-win8x4.hook.glsl"
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
dscale=ewa_lanczos

**Comment by Artoriuz** [comment]
Switch to gpu-next.
