### ISSUE TITLE
Request: add antiringing to the DS variants

### ISSUE THREAD

**Issue by raziel711** [Artoriuz/ArtCNN#31]
I was wondering if you would consider adding a tunable PixelClipper filter to the DS variants.  I've noticed that the sharpening done by the DS variants can noticeably sharpen any ringing artifacts present in the source, especially with DVD encodes.  For example:  

ewa_lanczossharp:
![ewa_lanczossharp](https://github.com/user-attachments/assets/f76bc508-c287-470c-8b67-d77338e11491)

ArtCNN_C4F16_CMP:
![ArtCNN_C4F16_CMP](https://github.com/user-attachments/assets/e033b218-e279-42d0-acdb-9e75fdfe85c6)

ArtCNN_C4F16_DS_CMP:
![ArtCNN_C4F16_DS_CMP](https://github.com/user-attachments/assets/f34cfbae-87fb-4123-87b2-8a3d92528131)

Obviously the source itself is garbage, and I'm sure that the DS variants were never intended to be used on content like that; however, if the antiringing filter could end up removing some of the ringing in the source, it could help make the DS variants safer to use on low resolution videos.

**Comment by Artoriuz** [comment]
The reason I haven't added it back is because AR is often detrimental when paired with a CNN, but yeah it can sometimes help depending on the source.

Please try this and see if it helps you: [ArtCNN_C4F16_DS_AR_CMP.txt](https://github.com/user-attachments/files/17027704/ArtCNN_C4F16_DS_AR_CMP.txt)

**Comment by raziel711** [comment]
ArtCNN_C4F16_DS_AR_CMP:
![ArtCNN_C4F16_DS_AR_CMP](https://github.com/user-attachments/assets/cc75f652-7d2a-41be-992f-6f2dd4f688d0)

It does deal with the ringing in the source a bit better, but there is also a visible increase in the amount of aliasing, which is probably unavoidable.  Overall, I do agree that the AR seems to be a net negative, at least with the DVD encodes I tried it on. Thank you for posting the shader so I could test it.
