### ISSUE TITLE
Model Proto issue

### ISSUE THREAD

**Issue by VisionHDR** [Artoriuz/ArtCNN#32]
I can't use the onnx in Windows/Python.

I get:

DecodeError: Error parsing message with type 'onnx.ModelProto'

Any solutions? even a simple Python model check fails.

I have every library installed.

import onnx
import onnxruntime as ort

model_path = r"C:\models\ArtCNN_R8F64.onnx"

try:
    
    with open(model_path, 'rb') as f:
        model_content = f.read()
    
    model = onnx.ModelProto()
    model.ParseFromString(model_content)
    
   
    onnx.checker.check_model(model)
    print("ONNX model is valid and loaded successfully.")
    
   
    session = ort.InferenceSession(model_path, providers=['CUDAExecutionProvider'])
    print("ONNX Runtime session created successfully.")
    
except Exception as e:
    print(f"Error loading ONNX model: {e}")

**Comment by Artoriuz** [comment]
Try chainner with onnx runtime, it works on my machine™.
