### ISSUE TITLE
ArtCNN shaders makes no visible changes in MPV.

### ISSUE THREAD

**Issue by acedogblast** [Artoriuz/ArtCNN#33]
Hello I have been trying to get the glsl shaders to work on MPV. I have Anime4K mode A to work and it produces very visible changes to the original image however I am unable to see any visible changes when using ArtCNN. This is with a OLED 3440x1440p monitor full screen.

This is my mpv input.conf file:
```
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode A (HQ)"

CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F32_DS.glsl"; show-text "ArtCNN"

CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
```

And here is my mpv.conf file:
```
input-ipc-server=/tmp/mpvsocket
demuxer-max-bytes=500000KiB
vo=gpu-next
gpu-context=waylandvk
gpu-api=vulkan
cache=yes
target-colorspace-hint
profile=pseudo-gui
hwdec=auto
screenshot-format=png
screenshot-high-bit-depth=no
```

MPV with verbose output on the commands line shows no errors.

Here are screenshots to compare the output
Original:
![Original](https://github.com/user-attachments/assets/8a7b35bf-247b-424a-a042-705e250cc202)
Anime4K mode A:
![Anime4K](https://github.com/user-attachments/assets/f201617b-0a0a-496f-845c-e9789107c0c9)
ArtCNN_C4F32_DS:
![ArtCNN](https://github.com/user-attachments/assets/3edc00f6-b9cb-4746-916a-77fcbb955e74)

I have also tried [ArtCNN_C4F32_DS_CMP](https://github.com/Artoriuz/ArtCNN/blob/main/GLSL/Compute/ArtCNN_C4F32_DS_CMP.glsl) and it also gives me no visible changes.
Do I have the shader for ArtCNN configured correctly?

**Comment by Jules-A** [comment]
I think you need to get your eyes checked, ArtCNN is quite clearly applying, however the difference won't be anywhere near as pronounced as Anime4k as ArtCNN shaders try to preserve as much detail as possible while upscaling. Anime4k (restore) shaders destroy a tonne of detail and often leads to absurd artifacts.

**Comment by acedogblast** [comment]
Can you post some zoomed cropped parts of the images I posted comparing the original to ArtCNN? I may just be expecting sharpened line art since I am used to Anime4K and that is the visual metric I use to determine upscaling quality for anime content.

There also is a lack of any samples of ArtCNN anywhere on the internet. The README of this repository also lacks any sample pictures.

**Comment by utuhiro78** [comment]
> I am unable to see any visible changes when using ArtCNN.

Upscalers doesn't make a big difference if you play a high resolution movie.
Play a 480p movie in full screen mode. You'll see a big difference.
Install [yt-dlp](https://github.com/yt-dlp/yt-dlp) and run it.

```
mpv --ytdl-format=244+251 https://www.youtube.com/watch?v=ue4irL_g-UE --start=00:04:38 --fs --pause
```

**Comment by Artoriuz** [comment]
The condition for the shaders to trigger is `//!WHEN OUTPUT.w LUMA.w / 1.3 > OUTPUT.h LUMA.h / 1.3 > *`, anything lower than a 1.3x scaling factor will make mpv skip them.

**Comment by acedogblast** [comment]
@Artoriuz Thanks for the clarification. The source resolution in my example is 1920x1080 the final display resolution is effectively 2560x1440 which is 1.33x scaling factor so the shaders should trigger unless there is a rounding error? I will try out some older SD anime videos.

Additionally it would be nice if you could post some sample images comparing the upscale vs traditional upscale (like bicubic, lazcos. etc.) on this repo so we can get a better idea at what the shader/models should do.

**Comment by Artoriuz** [comment]
If you're doubling and then downscaling with hermite it might be difficult to notice depending on how blurry the source is.

**Comment by Jules-A** [comment]
> Can you post some zoomed cropped parts of the images I posted comparing the original to ArtCNN?

Apologies for the awful proportions but it's pretty easy to see by the reduced noise (since you are using the denoise variant).
Normally you'd judge by other means but like Artoriuz already said, hermite downscaling isn't really doing it any favours, it's not really that great for anime imo since it can leave the lines with a sort of furriness to them instead of being smooth.

No shaders
![Capture](https://github.com/user-attachments/assets/ade0baeb-2e0c-422f-820d-a66aa6caca4f)

ArtCNN
![Capture2](https://github.com/user-attachments/assets/4edeb14f-059e-452b-bb31-620a210fb56d)

**Comment by acedogblast** [comment]
@Jules-A Thanks for the pictures. It seems I have misunderstood the intended purpose of ArtCNN which is to preserve/restore original details that are lost from traditional scalling artifacts.

I originally thought ArtCNN is a more advanced form of upscaling SRGAN with same end goal as anime4k which sharpen line art at the cost of loss of fine details. So having a very minute change from MPV's default scaler was the expected result.

**Comment by Jules-A** [comment]
> I originally thought ArtCNN is a more advanced form of upscaling SRGAN with same end goal as anime4k which sharpen line art at the cost of loss of fine details. So having a very minute change from MPV's default scaler was the expected result.

It is affecting the lines quite a bit but it's nowhere near as harsh as SRGAN, however you are downscaling after it scales with the default Hermite which loses quite a bit of sharpness and can make the lines furry. Try downscaling with something like ewa_robidoux or catmull_rom (with anti-ringing enabled) if want it to look more pronounced or try up-scaling 720p anime.
