### ISSUE TITLE
Attempting to activate the shader crashes MPV

### ISSUE THREAD

**Issue by KiwiDaBirb** [Artoriuz/ArtCNN#34]
I'm on a 7900XTX with graphics driver version 24.12.1 on the latest nightly MPV on windows11.
Attempting to activate _any version_ of the shader when MPV is in fullscreen results in MPV crashing, and a Microsoft Visual C++ Runtime Library Assertion failed error to appear. 
![image](https://github.com/user-attachments/assets/0d110a4e-e8b5-4395-8026-c6dafe6f312a)
Enabling while in native video res windowed view does not appear to crash, though it will very quickly do so when enlarging the window by dragging the corner.

I have my shaders set up in my config file so:
`CTRL+1 no-osd change-list glsl-shaders clr ""; no-osd change-list glsl-shaders set "~/AppData/Roaming/mpv/shaders/FSR.glsl"; show-text "FSR"`

`CTRL+2 no-osd change-list glsl-shaders clr ""; no-osd change-list glsl-shaders set "~/AppData/Roaming/mpv/shaders/ArtCNN_C4F16_CMP.glsl"; show-text "ArtCNN"`

`CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"`

**Comment by KiwiDaBirb** [comment]
Resolved by having `vo=gpu-next` in mpv.conf.
Another issue described the shaders simply not working, not a crash, but that ended up being what contained the solution. Apologies!

This explains the window resizing not instantly crashing for anyone who happens to run across this:
![image](https://github.com/user-attachments/assets/083c5447-bd05-4462-9bfd-6b2a3858d278)

**Comment by Artoriuz** [comment]
Yeah, I can confirm the same happens here on `vo=gpu`. That looks like an mpv issue to me.
