### ISSUE TITLE
it seem to have issues with rigning.

### ISSUE THREAD

**Issue by mightyhuhn** [Artoriuz/ArtCNN#5]
test file:
[sd.zip](https://github.com/Artoriuz/ArtCNN/files/14144288/sd.zip)
results:
https://slow.pics/c/X8waASMt
all NN scaler fail here. so this filter is not an outliner.
edit: fixed one image.

**Comment by Artoriuz** [comment]
If you still end up having issues with ringing when actually using the shader just be reminded that it has built-in AR which you can control with `--glsl-shader-opts` (or edit the default value in the shader body itself).

**Comment by mightyhuhn** [comment]
only 1 image was wrong.
they all ringing now. i was testing all mode in 16 to be fair and mistyped for sh.
the comparisons will be in the opening post.

the casual 0.35 below?
//!PARAM ar_strength
//!TYPE float
//!MINIMUM 0.0
//!MAXIMUM 1.0

**Comment by Artoriuz** [comment]
Yeah it's set very low by default to prevent hurting fine detail generation, but you can crank it up to get rid of ringing if the ringing is coming from the model.

**Comment by mightyhuhn** [comment]
even at 1 it has barely any effect on this image.
i used this to change it:

CTRL+5 change-list glsl-shader-opts set "ar_strength=1";
CTRL+6 change-list glsl-shader-opts set "ar_strength=0";
it changes something so it should be the correct usage.

**Comment by Artoriuz** [comment]
That's because the ringing is in the source.

This is literally how it looks like without any scaling:
![Screenshot 2024-02-02 174359](https://github.com/Artoriuz/ArtCNN/assets/12078193/9a807dd3-efc9-45b1-b5b0-cafd3ca08ede)

**Comment by mightyhuhn** [comment]
i know the source has ringing alot of ringing typical anime dvd. if a NN scaler adds ringing where a dumb scaler doesn't that's the issue here the major example:
![16mini](https://github.com/Artoriuz/ArtCNN/assets/4950090/5b7712da-6469-4560-99d1-6569853461c5) ![jinc mini](https://github.com/Artoriuz/ArtCNN/assets/4950090/6755cead-484d-4dec-8020-efe090bc6a9e)

![16mini300](https://github.com/Artoriuz/ArtCNN/assets/4950090/0bb9198b-9f2f-4ba8-adb6-03ad92b599a7)
![jinc mini300](https://github.com/Artoriuz/ArtCNN/assets/4950090/103b9fea-8fa6-4c7f-8619-584b96772bdd)

**Comment by Artoriuz** [comment]
The normal FIR filter is just blurring the ringing out, the CNNs are respecting the content.

I could train a variant of ArtCNN to get rid of source ringing though.

**Comment by mightyhuhn** [comment]
well i guess so NN is not really ringing they don't work like jinc here in comparison.
but i simply can not agree that this is respecting the content in this case this is not source ringing and the NN scaler are just smoothing it over.

if i look at the normal sized x2 image i see a black bar on the middle of the white letters. objectively it there is no black bar it is just a little bit darker.

most likely just an edge case here it looks wrong. i don't know the correct term.
