### ISSUE TITLE
Luma Doubler

### ISSUE THREAD

**Issue by crazysword1** [Artoriuz/ArtCNN#6]
Hi,
You mentioned the following on your page.

**If you plan on using ArtCNN for fractional scaling factors below 2x, it's recommended that you change the default dscale from hermite to a sharper option to avoid blurring the image.**

How do you change the dscale from hermite to something else? I tried to look for hermite in the glsl but didn't find it.

Also, what would you recommend changing it too for a sharp picture with the best possible subjective quality if performance isn't a consideration?

Thanks

**Comment by Artoriuz** [comment]
`dscale` is an mpv option: https://mpv.io/manual/master/

By default it's set to `hermite`, which is generally very safe but also a bit blurry. To be honest I should probably just remove this remark from the readme.

You can just add something like `dscale=catmull_rom` to your config if you want a sharper downsampling filter. This is already on the limit of what you can use in linear light (another mpv default) without ringing way too hard. 

In theory the best option taking only downsampling quality into consideration would be some kind of polar Jinc-Jinc with AR enabled. I don't know which one though. You can read more about this here: https://legacy.imagemagick.org/Usage/filter/nicolas/#downsample
