### ISSUE TITLE
Issues with mpv?

### ISSUE THREAD

**Issue by arianaa30** [Artoriuz/ArtCNN#7]
Interesting work! I was just going to test it out with MPV on some 360p videos. Added it into input.conf along with other shaders. But it shows a blue screen:
Is there an issue with this? All other work except this. I tried all variations and sizes.

```
...
...
CTRL+5 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_3DGraphics_Upscale_x2_US.glsl"; show-text "Anime4K 3D: Mode E (HQ)"
CTRL+6 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F8_LL.glsl"; show-text "ArtCNN: ArtCNN"

```

**Comment by hooke007** [comment]
Incompatible with vo_gpu

https://github.com/Artoriuz/ArtCNN?tab=readme-ov-file#instructions

**Comment by Artoriuz** [comment]
To be honest I don't know what exactly the issue is, but this is likely more related to `vo=gpu` than with the shader since it works fine on `gpu-next`.

I'd recommending asking one of the mpv devs about it, but good luck finding someone who actually cares about `vo=gpu`.
