### ISSUE TITLE
combination with other shaders?

### ISSUE THREAD

**Issue by arianaa30** [Artoriuz/ArtCNN#8]
Given that these are "upscaling" shaders, can we combine them with other shaders and use in mpv? I would like to add it to some Restore and Denoising shaders (e.g. from Anime4K) and pipeline them together.

**Comment by Artoriuz** [comment]
ArtCNN has a variant that denoises and sharpens while upscaling, I'd probably try it first before mixing it with other things.

But yes, you should be able to do this just fine.
